# Generated by Django 4.2.1 on 2023-12-02 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(choices=[('State Bank of India', 'SBI'), ('HDFC Bank', 'HDFC'), ('ICICI Bank', 'ICICI'), ('Punjab National Bank', 'PNB'), ('Axis Bank', 'Axis'), ('Canara Bank', 'Canara'), ('Bank of Baroda', 'BoB'), ('Union Bank of India', 'UBI'), ('IDBI Bank', 'IDBI'), ('Kotak Mahindra Bank', 'Kotak'), ('IndusInd Bank', 'IndusInd'), ('Yes Bank', 'Yes'), ('Bank of India', 'BOI'), ('Central Bank of India', 'CBI'), ('Indian Bank', 'Indian Bank'), ('Federal Bank', 'Federal'), ('Karur Vysya Bank', 'KVB'), ('Punjab & Sind Bank', 'PSB'), ('UCO Bank', 'UCO'), ('DBS Bank India', 'DBS')], max_length=100)),
                ('account_number', models.CharField(max_length=25)),
                ('ifsc', models.CharField(max_length=25)),
                ('card_number', models.CharField(max_length=25)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_month', models.CharField(choices=[('01', 'JAN'), ('02', 'FEB'), ('03', 'MAR'), ('04', 'APR'), ('05', 'MAY'), ('06', 'JUN'), ('07', 'JUL'), ('08', 'AUG'), ('09', 'SEP'), ('10', 'OCT'), ('11', 'NOV'), ('12', 'DEC')], max_length=100)),
                ('expiry_year', models.IntegerField()),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('banner_photo', models.ImageField(upload_to='movie_banners/')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenDetails',
            fields=[
                ('screen_id', models.AutoField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=100)),
                ('seat_count', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('', 'Select State'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', max_length=100)),
                ('status', models.CharField(default='Inactive', max_length=10)),
                ('pancard', models.ImageField(blank=True, upload_to='business_pan/')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('Economy', 'Economy'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('VIP', 'VIP'), ('Deluxe', 'Deluxe'), ('Royal', 'Royal')], default='Economy', max_length=50)),
                ('rate', models.IntegerField()),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='SlotDetails',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='A', max_length=2)),
                ('seat_number', models.IntegerField(default=1)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.screendetails')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.ticketdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ShowDetails',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_timing', models.TimeField()),
                ('movie', models.ManyToManyField(to='adminpanel.moviedetails')),
                ('screen', models.ManyToManyField(to='adminpanel.screendetails')),
            ],
        ),
        migrations.AddField(
            model_name='screendetails',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.theatre'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('', 'Select State'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', max_length=100)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('id_proof', models.ImageField(blank=True, upload_to='customer_identifier/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Booked', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.customer')),
                ('slot', models.ManyToManyField(to='adminpanel.slotdetails')),
            ],
        ),
    ]
