# Generated by Django 4.2.1 on 2023-12-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='banner_photo',
            field=models.ImageField(null=True, upload_to='movie_banners/'),
        ),
    ]
