# Generated by Django 4.1.5 on 2023-12-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_moviedetails_banner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdetails',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.ticketdetails'),
        ),
    ]
