# Generated by Django 4.1.5 on 2023-12-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_slotdetails_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetails',
            name='rate',
            field=models.IntegerField(default=110),
        ),
    ]
