# Generated by Django 4.1.5 on 2023-12-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_ticketdetails_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetails',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
