# Generated by Django 4.1.5 on 2023-12-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_movie_theaters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie_theaters',
        ),
    ]
