# Generated by Django 4.1.5 on 2023-12-19 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_delete_movie_theaters'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_theaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.moviedetails')),
                ('theaters', models.ManyToManyField(to='adminpanel.theatre')),
            ],
        ),
    ]
