# Generated by Django 4.1.5 on 2023-12-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_movie_theaters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie_theaters',
            new_name='MovieTheaters',
        ),
    ]
