# Generated by Django 4.1.5 on 2023-12-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_rename_movie_theaters_movietheaters'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='seat_capacity',
            field=models.IntegerField(default=60),
        ),
    ]
