# Generated by Django 4.1.5 on 2023-12-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_theatre_seat_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='seat_capacity',
            field=models.IntegerField(default=260),
        ),
    ]
