# Generated by Django 4.1.5 on 2023-12-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_alter_theatre_seat_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='seats',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_name', models.CharField(max_length=100)),
            ],
        ),
    ]
