# Generated by Django 4.1.5 on 2023-12-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_seats',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_name', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='seats',
        ),
    ]
