# Generated by Django 4.1.5 on 2023-12-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_user_seats_delete_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='seats',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_name', models.TextField()),
            ],
        ),
    ]
