# Generated by Django 4.1.5 on 2023-12-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='seat_id',
        ),
        migrations.AlterField(
            model_name='seats',
            name='seat_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
