# Generated by Django 4.1.5 on 2023-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_remove_seats_seat_id_alter_seats_seat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_seats',
            name='seat_id',
        ),
        migrations.AddField(
            model_name='user_seats',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
