# Generated by Django 4.1.5 on 2023-12-19 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0016_remove_user_seats_seat_id_user_seats_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_seats',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
