# Generated by Django 4.1.5 on 2023-12-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_alter_user_seats_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=40)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.IntegerField(max_length=12)),
                ('feed_message', models.TextField()),
                ('rating', models.IntegerField(max_length=5)),
            ],
        ),
    ]
