# Generated by Django 4.1.5 on 2023-12-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feed_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
