# Generated by Django 4.1.5 on 2023-12-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_alter_feedback_feed_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='customer_phone',
        ),
    ]
