# Generated by Django 4.1.5 on 2023-12-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_remove_feedback_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
