# Generated by Django 4.1.5 on 2023-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='screendetails',
            name='screen_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
