# Generated by Django 4.1.5 on 2023-12-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_alter_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_seats',
            name='audi_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.screendetails'),
            preserve_default=False,
        ),
    ]
