# Generated by Django 4.1.5 on 2023-12-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_user_seats_audi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_seats',
            name='time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
