# Generated by Django 4.1.5 on 2023-12-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_user_seats_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_seats',
            name='date_field',
            field=models.DateField(default=None),
        ),
    ]
