# Generated by Django 4.1.5 on 2023-12-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_user_seats_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='theatre_name',
            field=models.CharField(default=1, max_length=234, unique=True),
            preserve_default=False,
        ),
    ]
